version: '3.9'

services:
  grabber-dev:
    build:
      context: ..
      dockerfile: .devcontainer/mt-grabber-dev/Dockerfile
    volumes:
      - ../:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh
    command: sleep infinity
    links:
      - db
    env_file: .env

  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5500:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db
    env_file: .env

  db-dev:
    build:
      context: ..
      dockerfile: .devcontainer/mt-db-dev/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/node/.ssh
      - db-dev-node-modules:/workspace/mt-db/node_modules
    depends_on:
      - db
    command: sleep infinity
    env_file: .env

volumes:
  db-data:
  pgadmin-data:
  db-dev-node-modules: