version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh
    command: sleep infinity
    links:
      - db
    env_file: .env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5500:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db
    env_file: .env

volumes:
  postgres-data:
  pgadmin-data: